Repository AdaSupport/docs, pull requests merged in 2019-05, with the labels that each got.

#26 Add example code
  ada-embed.md
  api/metavariables.md
Labels: size/S

#27 updates jsfiddle link
  ada-embed.md
Labels: size/XS

#28 fixes incorrect jsfiddle links on embd-script docs
  ada-embed.md
Labels: size/XS

#29 Add dragAndDrop to docs
  ada-embed.md
Labels: size/S

#30 Adds info regarding errors
  api/metavariables.md
Labels: size/M
